<div class="contenedor-iniciarsesion">
  <form action="" method="post" name="FormEntrar">
      <div class="img-perfil">
      <img src="<?php echo $_layoutParams['ruta_img']; ?>login.png">
      </div>
      
      <input type="hidden" name="iniciarsesion" value="1" />
      <div class="I-Usuario icon-user">
          <input type="text" name="correo_usuario" placeholder="Ingrese su correo o Usuario." value="<?php if(isset($this->Datos['correo_usuario'])) echo $this->Datos['correo_usuario']; ?>">
      </div>
      <div class="I-Contrasena icon-lock">
          <input type="password" name="contrasena" placeholder="Ingrese su contraseña">
      </div>
    
      <input type="submit" class="btn-iniciarsesion" name="inises" value="LOGIN">
          <p><div class="opcn-cntrsn"><a href="">¿Olvidaste tu contraseña?</a></div>
          <p><div class="opcn-rgstrrs"><a href="<?php echo BASE_URL . 'micuenta/registrarse'; ?>" class="<?php echo $Estilo; ?>">Registrarse.</a></div></p>
</form>

</div>


